### ISSUE TITLE
Find a better naming

### ISSUE THREAD

**Issue by josepjaume** [codegram/gherkin-ruby#1]
To be able to differenciate this from the "original" gherkin parser

**Comment by divins** [comment]
Spinachs with:
champignon
chickpea
...

**Comment by txus** [comment]
Since we want to encourage the idea that it's the same language (you don't have to learn a new one), it must stay (a subset of) the Gherkin language.

Gherkin-ruby means "the Gherkin language, the one you already know, but implemented in Ruby".
