### ISSUE TITLE
Rename 'gherkin.rb' to 'gherkin-ruby.rb'

### ISSUE THREAD

**Issue by mjbellantoni** [codegram/gherkin-ruby#19]
The `gherkin-ruby` gem is colliding with the `gherkin` gem because they both use `gherkin.rb` as their primary file to be required.

(I'm trying to migrate from Cucumber to Spinach piecemeal and this is keeping me from doing that.)

I'm happy to make this change (here and in Spinach) if someone gives the thumbs-up.

**Comment by txus** [comment]
Thumbs up! :)

**Comment by txus** [comment]
@mjbellantoni what's the status on this?
