### ISSUE TITLE
Add support for tags

### ISSUE THREAD

**Issue by josepjaume** [codegram/gherkin-ruby#2]
Make the parser support tags

**Comment by divins** [comment]
I'll try! :D

**Comment by divins** [comment]
Do you think that is useful to have multiple tags in an scenario? 
I still have to take a look at how we implemented tag support so, multiple tags would be handled by Spinach right now?

@javascript @guide @navigation
scenario: User reaches post creation
...

**Comment by divins** [comment]
Closed by #3
