### ISSUE TITLE
Support Tables or Document Not Supporting Tables

### ISSUE THREAD

**Issue by cosmocracy2000** [codegram/gherkin-ruby#23]
Hi.  I spent a couple of hours considering switching to Spinach until I learned that you're not supporting the Gherkin table syntax.  I find tables immensely valuable for specifying the nitty-gritty details of a data-intensive test case that would waste a lot of space (and have horrible readability) in narrative format.

Please either consider adding tables OR state clearly in your documentation that they are purposely Not Supported.

Thank you.  (This project looked promising)

**Comment by dyba** [comment]
To the repo owners, please give us some direction as to what we need to know in order to add this functionality to spinach. See #24.
