### ISSUE TITLE
Support multiple languages

### ISSUE THREAD

**Issue by txus** [codegram/gherkin-ruby#6]

**Comment by mrcasals** [comment]
Any idea on how to start working on this?

**Comment by mrcasals** [comment]
I need this, I'll start working on it and ask form help if I get stuck... But it looks like I should start from here, right? 

https://github.com/codegram/gherkin-ruby/blob/master/lib/gherkin/parser/lexer.rb#L61-104

**Comment by txus** [comment]
We need to hook into the lexer ([defined here](https://github.com/codegram/gherkin-ruby/blob/master/lib/gherkin/parser/gherkin.rex), the file you mentioned is autogenerated from this one) to identify the header like:

```
# language: ca
Feature: Fer alguna cosa
```

And then use the corresponding set of tokens. The lexer is written in [Rexical](https://github.com/tenderlove/rexical), so we just need to figure out how to execute some code _before_, dynamically set which set of tokens are we using, and then let the lexer tokenize the file, and then we're done. Makes sense?

**Comment by txus** [comment]
Actually it's very easy, look at [this part of the code](https://github.com/codegram/gherkin-ruby/blob/master/lib/gherkin/parser/gherkin.rex#L35-42). Here, before the call to `scan_setup(code)`, we should define an instance variable with a hash or something like this:

``` ruby
locale = code.scan(/language/ bla bla whatever
@tokens = get_tokens_from_locale(locale) # => this would return something like { :When => "Quan", :Then => "Llavors" ... }
scan_setup(code)
```

And then I don't know how to use these tokens in the lexer. But it's something. What do you think?

**Comment by mrcasals** [comment]
Looks nice to me, but I don't see myself succeeding on this alone...

## 

Marc Riera Casals

**Comment by txus** [comment]
Just a small status update, anyone up for implementing this? @mrcasals @Dor3nz @divins @oriolgual @josepjaume ?

**Comment by oriolgual** [comment]
We haven't actually needed this, so.... :P

**Comment by mrcasals** [comment]
I do have needed this, but I don't know how to fixnit :(

**Comment by jmgarnier** [comment]
Sorry, I will not contribute because I'm working on my own vegetable: a Gherkin DSL on top of RSpec: https://github.com/21croissants/maniok_bdd/

**Comment by oriolgual** [comment]
OK, nevermind.

**Comment by RunsFor** [comment]
Hi,

I'm wondering if this feature are planned to be implemented?
